name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up C++ toolchain
      run: sudo apt-get install -y g++ libboost-all-dev
    - name: Set up CMake
      run: sudo apt-get install -y cmake
    - name: Configure
      run: cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    - name: Build
      run: cmake --build . --config Release
    - name: Run Tests
      uses: ./.github/workflows/test.yml
    # - name: Upload Coverage Report
    #   uses: codecov/codecov-action@v1
    #   with:
    #     token: ${{ secrets.CODECOV_TOKEN }}